### ISSUE TITLE
Just for info some cmd -> cmdj

### ISSUE THREAD

**Issue by Maijin** [mtalbi/pwnpam#1]
Just for info those command have json equivalent for better code:

rip = r2.cmd("dr rip")
-> drj

raw = r2.cmd("puf").replace('%', '')
-> p8f or p8fj

ret = r2.cmd('afi')
-> afij (or even aflj as it contains the same info in one time)

**Comment by mtalbi** [comment]
Hi Maijin,

Sorry for the delayed answer. This is my first attempt in using radare2 and r2pipe.

Thanks for the tips. Will push ASAP the suggested improvements.

**Comment by Maijin** [comment]
No problem just wanted you to know ;) Feel free to join https://telegram.me/radare or #radare on Freenode
